"""PDF 查重工作流的稳定模型输入入口。"""

from app.agent.pdf_deduplication.prompt.full_document import (
    FULL_DOCUMENT_JUDGMENT_PROMPT_VERSION,
    FULL_DOCUMENT_JUDGMENT_STRATEGY_PROMPT,
    FULL_DOCUMENT_TOOL_INSTRUCTION_PROMPT,
    FULL_DOCUMENT_TOOL_PLACEMENT,
    FullDocumentJudgmentPromptVersion,
    append_full_document_candidate_pdf,
    append_full_document_judgment_strategy,
    build_full_document_judgment_messages,
)
from app.agent.pdf_deduplication.prompt.page_embedding import (
    PDF_PAGE_EMBEDDING_INPUT_VERSION,
    PDF_PAGE_EMBEDDING_SYSTEM_INSTRUCTION,
    PDFPageEmbeddingInputVersion,
    build_pdf_page_embedding_messages,
)
from app.agent.pdf_deduplication.prompt.page_navigation import (
    CANDIDATE_GUIDE_END_DIVIDER,
    CANDIDATE_GUIDE_START_DIVIDER,
    PAGE_NAVIGATION_JUDGMENT_PROMPT_VERSION,
    PAGE_NAVIGATION_JUDGMENT_STRATEGY_PROMPT,
    PAGE_NAVIGATION_TOOL_INSTRUCTION_PROMPT,
    PAGE_NAVIGATION_TOOL_PLACEMENT,
    PageNavigationJudgmentPromptVersion,
    append_candidate_document_guide,
    append_page_navigation_judgment_strategy,
    append_page_navigation_round_context,
    build_page_navigation_judgment_messages,
)
from app.agent.pdf_deduplication.prompt.relation_standard import (
    CANDIDATE_CONTRACT_END_DIVIDER,
    CANDIDATE_CONTRACT_INPUT_HEADER,
    CANDIDATE_CONTRACT_LABEL,
    CANDIDATE_CONTRACT_START_DIVIDER,
    CONTRACT_RELATION_STANDARD_PROMPT,
    CONTRACT_RELATION_STANDARD_VERSION,
    ContractRelationStandardVersion,
    TOOL_INSTRUCTION_START_DIVIDER,
    UPLOADED_CONTRACT_LABEL,
    UPLOADED_CONTRACT_END_DIVIDER,
    append_contract_relation_standard,
)

__all__ = [
    "CANDIDATE_CONTRACT_END_DIVIDER",
    "CANDIDATE_CONTRACT_INPUT_HEADER",
    "CANDIDATE_CONTRACT_LABEL",
    "CANDIDATE_CONTRACT_START_DIVIDER",
    "CANDIDATE_GUIDE_END_DIVIDER",
    "CANDIDATE_GUIDE_START_DIVIDER",
    "CONTRACT_RELATION_STANDARD_PROMPT",
    "CONTRACT_RELATION_STANDARD_VERSION",
    "ContractRelationStandardVersion",
    "FULL_DOCUMENT_JUDGMENT_PROMPT_VERSION",
    "FULL_DOCUMENT_JUDGMENT_STRATEGY_PROMPT",
    "FULL_DOCUMENT_TOOL_INSTRUCTION_PROMPT",
    "FULL_DOCUMENT_TOOL_PLACEMENT",
    "FullDocumentJudgmentPromptVersion",
    "PDFPageEmbeddingInputVersion",
    "PDF_PAGE_EMBEDDING_INPUT_VERSION",
    "PDF_PAGE_EMBEDDING_SYSTEM_INSTRUCTION",
    "PAGE_NAVIGATION_JUDGMENT_PROMPT_VERSION",
    "PAGE_NAVIGATION_JUDGMENT_STRATEGY_PROMPT",
    "PAGE_NAVIGATION_TOOL_INSTRUCTION_PROMPT",
    "PAGE_NAVIGATION_TOOL_PLACEMENT",
    "PageNavigationJudgmentPromptVersion",
    "TOOL_INSTRUCTION_START_DIVIDER",
    "UPLOADED_CONTRACT_LABEL",
    "UPLOADED_CONTRACT_END_DIVIDER",
    "append_full_document_candidate_pdf",
    "append_candidate_document_guide",
    "build_pdf_page_embedding_messages",
    "append_contract_relation_standard",
    "append_full_document_judgment_strategy",
    "append_page_navigation_judgment_strategy",
    "append_page_navigation_round_context",
    "build_full_document_judgment_messages",
    "build_page_navigation_judgment_messages",
]
